// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/chat/v1beta1/ibc.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TextMessagePacketData struct {
	SourceChainId string `protobuf:"bytes,1,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	Id            uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	FromAddress   string `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Text          string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	SendAt        uint64 `protobuf:"varint,6,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
}

func (m *TextMessagePacketData) Reset()         { *m = TextMessagePacketData{} }
func (m *TextMessagePacketData) String() string { return proto.CompactTextString(m) }
func (*TextMessagePacketData) ProtoMessage()    {}
func (*TextMessagePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d1d0d24fe59706d, []int{0}
}
func (m *TextMessagePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TextMessagePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TextMessagePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TextMessagePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMessagePacketData.Merge(m, src)
}
func (m *TextMessagePacketData) XXX_Size() int {
	return m.Size()
}
func (m *TextMessagePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMessagePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_TextMessagePacketData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TextMessagePacketData)(nil), "gaia.chat.v1beta1.TextMessagePacketData")
}

func init() { proto.RegisterFile("gaia/chat/v1beta1/ibc.proto", fileDescriptor_4d1d0d24fe59706d) }

var fileDescriptor_4d1d0d24fe59706d = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x86, 0x27, 0xfd, 0xfa, 0x55, 0x1a, 0xff, 0x30, 0x28, 0x0e, 0x15, 0x63, 0x55, 0x90, 0xae,
	0x26, 0x14, 0xaf, 0xa0, 0xfe, 0x2c, 0x5c, 0x08, 0x52, 0x5c, 0xb9, 0x19, 0x32, 0x49, 0x9a, 0x06,
	0x9d, 0x9e, 0x32, 0x39, 0x95, 0x7a, 0x17, 0x5e, 0x86, 0x57, 0xe1, 0xba, 0xcb, 0x2e, 0x5d, 0xea,
	0xf4, 0x46, 0x64, 0x32, 0xea, 0xee, 0xbc, 0xef, 0xf3, 0x84, 0xc0, 0x4b, 0x0f, 0xac, 0x74, 0x52,
	0xa8, 0xb1, 0x44, 0xf1, 0xdc, 0xcf, 0x0c, 0xca, 0xbe, 0x70, 0x99, 0x4a, 0xa6, 0x05, 0x20, 0xb0,
	0x9d, 0x0a, 0x26, 0x15, 0x4c, 0x7e, 0x60, 0x67, 0xd7, 0x82, 0x85, 0x40, 0x45, 0x75, 0xd5, 0x62,
	0xe7, 0xc8, 0x02, 0xd8, 0x27, 0x23, 0x42, 0xca, 0x66, 0x23, 0x81, 0x2e, 0x37, 0x1e, 0x65, 0x3e,
	0xad, 0x85, 0x93, 0x77, 0x42, 0xf7, 0xee, 0xcd, 0x1c, 0x6f, 0x8d, 0xf7, 0xd2, 0x9a, 0x3b, 0xa9,
	0x1e, 0x0d, 0x5e, 0x49, 0x94, 0xec, 0x8c, 0x6e, 0x7b, 0x98, 0x15, 0xca, 0xa4, 0x6a, 0x2c, 0xdd,
	0x24, 0x75, 0x3a, 0x26, 0x5d, 0xd2, 0x6b, 0x0f, 0x37, 0xeb, 0xfa, 0xb2, 0x6a, 0x6f, 0x34, 0xdb,
	0xa2, 0x0d, 0xa7, 0xe3, 0x46, 0x97, 0xf4, 0x9a, 0xc3, 0x86, 0xd3, 0xec, 0x98, 0x6e, 0x8c, 0x0a,
	0xc8, 0x53, 0xa9, 0x75, 0x61, 0xbc, 0x8f, 0xff, 0x85, 0x47, 0xeb, 0x55, 0x37, 0xa8, 0x2b, 0x76,
	0x48, 0x29, 0xc2, 0x9f, 0xd0, 0x0c, 0x42, 0x1b, 0xe1, 0x17, 0x33, 0xda, 0x44, 0x33, 0xc7, 0xf8,
	0x7f, 0x00, 0xe1, 0x66, 0xfb, 0x74, 0xcd, 0x9b, 0x89, 0x4e, 0x25, 0xc6, 0xad, 0xf0, 0x55, 0xab,
	0x8a, 0x03, 0xbc, 0xb8, 0x5e, 0x7c, 0xf1, 0xe8, 0xad, 0xe4, 0xd1, 0xa2, 0xe4, 0x64, 0x59, 0x72,
	0xf2, 0x59, 0x72, 0xf2, 0xba, 0xe2, 0xd1, 0x72, 0xc5, 0xa3, 0x8f, 0x15, 0x8f, 0x1e, 0x4e, 0xad,
	0xc3, 0xf1, 0x2c, 0x4b, 0x14, 0xe4, 0x42, 0x81, 0xcf, 0xc1, 0x8b, 0xb0, 0xed, 0xbc, 0x5e, 0x17,
	0x5f, 0xa6, 0xc6, 0x67, 0xad, 0x30, 0xc7, 0xf9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xb7,
	0x6d, 0x71, 0x77, 0x01, 0x00, 0x00,
}

func (m *TextMessagePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TextMessagePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TextMessagePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SendAt != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.SendAt))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SourceChainId) > 0 {
		i -= len(m.SourceChainId)
		copy(dAtA[i:], m.SourceChainId)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.SourceChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIbc(dAtA []byte, offset int, v uint64) int {
	offset -= sovIbc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TextMessagePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceChainId)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovIbc(uint64(m.Id))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	if m.SendAt != 0 {
		n += 1 + sovIbc(uint64(m.SendAt))
	}
	return n
}

func sovIbc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIbc(x uint64) (n int) {
	return sovIbc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TextMessagePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TextMessagePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TextMessagePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendAt", wireType)
			}
			m.SendAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIbc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIbc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIbc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIbc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIbc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIbc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIbc = fmt.Errorf("proto: unexpected end of group")
)
